version: '3.6'

services:
  db:
    image: postgres
    container_name: db_fortbrasil
    environment:
      - POSTGRES_USER=fortbrasil
      - POSTGRES_PASSWORD=fortbrasil
      - POSTGRES_DB=fortbrasil
    ports:
      - 5432:5432
    expose:
      - 5432

  api:
    container_name: backend_api
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: always


