version: '3.6'
services:
  api:
    build: .
    depends_on:
      - db
    ports:
      - 5000:5000
    restart: always

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
