"""change  type latitude and longitude

Revision ID: 2254058c4297
Revises: 04bca5505a6d
Create Date: 2021-02-21 12:27:09.214597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2254058c4297'
down_revision = '04bca5505a6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('establishment', 'latitude',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('establishment', 'longitude',
               existing_type=sa.BIGINT(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('establishment', 'longitude',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('establishment', 'latitude',
               existing_type=sa.Float(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    # ### end Alembic commands ###
