"""change column latitude and longitude establishment

Revision ID: 257507090165
Revises: 0f7c4e7464b6
Create Date: 2021-02-20 14:36:59.676612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '257507090165'
down_revision = '0f7c4e7464b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('establishment', 'latitude',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('establishment', 'longitude',
               existing_type=sa.BIGINT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('establishment', 'longitude',
               existing_type=sa.BIGINT(),
               nullable=True)
    op.alter_column('establishment', 'latitude',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
